"""CloudLens API Conventions - Shared Models, Enums, and RFC-7807/9457 Problem Details.

Enforces Prompt 34 / BBP Section 38:
- Nine standard error codes.
- RFC 7807/9457 problem-details error format.
- Uniform cursor pagination parameters.
- Response metadata envelope.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field

T = TypeVar("T")


class StandardErrorCode(StrEnum):
    """The nine standard platform API error codes with documented semantics (Prompt 34)."""

    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ProblemDetails(BaseModel):
    """RFC 7807/9457 Problem Details error payload."""

    type: str = Field(..., description="URI reference identifying the problem type")
    title: str = Field(..., description="Short, human-readable summary of problem type")
    status: int = Field(..., description="HTTP status code generated by origin server")
    detail: str = Field(..., description="Human-readable explanation specific to occurrence")
    instance: str = Field(..., description="URI reference identifying specific occurrence")
    code: StandardErrorCode = Field(..., description="Machine-readable platform error code")
    correlation_id: str = Field(..., description="Distributed tracing correlation ID")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(), description="UTC timestamp"
    )
    last_successful_ingestion_at: str | None = Field(
        default=None,
        description="Timestamp of last successful data ingestion when code is DATA_UNAVAILABLE",
    )
    invalid_params: list[dict[str, Any]] | None = Field(
        default=None,
        description="Validation errors breakdown for INVALID_REQUEST",
    )


class ResponseMetadata(BaseModel):
    """Platform response metadata block present on all responses (Prompt 34)."""

    period: str | None = Field(
        default=None, description="Billing or reporting window (e.g. YYYY-MM)"
    )
    cost_basis: str = Field(default="BILLED", description="Cost basis: BILLED or AMORTISED")
    currency: str = Field(default="USD", description="ISO 4217 currency code")
    is_currency_converted: bool = Field(
        default=False, description="Whether currency conversion was applied"
    )
    freshness_per_provider: dict[str, str] = Field(
        default_factory=dict,
        description="Data freshness timestamp per cloud provider (ISO 8601 UTC)",
    )
    access_filtering_occurred: bool = Field(
        default=False,
        description="Whether response was filtered or masked due to caller scope permissions",
    )
    is_approximate_total: bool = Field(
        default=False,
        description="Whether aggregation total is approximate due to in-flight sync or unmapped records",
    )


class PaginationParams(BaseModel):
    """Cursor-based pagination parameters with default 50 and maximum 500 (API-104)."""

    limit: int = Field(default=50, ge=1, le=500, description="Page size (default 50, maximum 500)")
    cursor: str | None = Field(default=None, description="Opaque cursor token for next page")


class CursorPage(BaseModel, Generic[T]):
    """Cursor-paginated container model."""

    items: list[T] = Field(default_factory=list, description="Page items")
    next_cursor: str | None = Field(
        default=None, description="Next page cursor token, or null if end"
    )
    total: int | None = Field(default=None, description="Total matching items if available")
    metadata: ResponseMetadata = Field(
        default_factory=ResponseMetadata,
        description="Response metadata block",
    )
