"""Default Seed Data Definitions for Enterprise Master Catalogues.

Provides standardized seed definitions for:
- FOCUS 1.0 Service Categories
- Canonical Units across all dimensionalities
- Core System Metrics
- All 29 Reconciled Pricing Dimensions (DIM-01 to DIM-29)
- Canonical Resource Types and default monitoring types across AWS, Azure, GCP, OCI
"""

from decimal import Decimal

from domain.catalogues.models import (
    AggregationMethod,
    Dimensionality,
    MetricDTO,
    PricingDimensionDTO,
    ResourceTypeDTO,
    ServiceCategoryDTO,
    ServiceDTO,
    ServiceMappingDTO,
    UnitDTO,
)

# ==============================================================================
# 1. FOCUS 1.0 Service Categories
# ==============================================================================

SEED_SERVICE_CATEGORIES: list[ServiceCategoryDTO] = [
    ServiceCategoryDTO(
        code="COMPUTE",
        name="Compute",
        description="Virtual machines, containers, serverless compute, and bare metal instances.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="STORAGE",
        name="Storage",
        description="Object storage, block volumes, file systems, and archival storage.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="NETWORKING",
        name="Networking",
        description="Virtual networks, load balancers, gateways, DNS, and CDN.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="DATABASE",
        name="Database",
        description="Relational, NoSQL, memory cache, and distributed database services.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="SECURITY_IDENTITY",
        name="Security & Identity",
        description="Identity and access management, key management, secrets, and firewalls.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="ANALYTICS",
        name="Analytics",
        description="Data warehousing, big data processing, data lakes, and business intelligence.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="AI_ML",
        name="AI & Machine Learning",
        description="Machine learning training, inference endpoints, and cognitive services.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="MANAGEMENT_GOVERNANCE",
        name="Management & Governance",
        description="Monitoring, logging, audit trails, policy enforcement, and cost management.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="INTEGRATION",
        name="Integration",
        description="Message queues, event streaming, workflow orchestration, and API gateways.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="DEVELOPER_TOOLS",
        name="Developer Tools",
        description="Build pipelines, code repositories, artifact registries, and deployment tooling.",
        is_focus_standard=True,
    ),
    ServiceCategoryDTO(
        code="OTHER",
        name="Other",
        description="Unclassified or miscellaneous cloud provider offerings.",
        is_focus_standard=True,
    ),
]


# ==============================================================================
# 2. Canonical Unit Catalogue Seeds
# ==============================================================================

SEED_UNITS: list[UnitDTO] = [
    # Digital Storage (Base: B)
    UnitDTO(
        symbol="B",
        name="Byte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="bytes",
        name="Bytes",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="KiB",
        name="Kibibyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1024"),
    ),
    UnitDTO(
        symbol="MiB",
        name="Mebibyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1048576"),
    ),
    UnitDTO(
        symbol="GiB",
        name="Gibibyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1073741824"),
    ),
    UnitDTO(
        symbol="TiB",
        name="Tebibyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1099511627776"),
    ),
    UnitDTO(
        symbol="PiB",
        name="Pebibyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1125899906842624"),
    ),
    UnitDTO(
        symbol="KB",
        name="Kilobyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1000"),
    ),
    UnitDTO(
        symbol="MB",
        name="Megabyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1000000"),
    ),
    UnitDTO(
        symbol="GB",
        name="Gigabyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1000000000"),
    ),
    UnitDTO(
        symbol="TB",
        name="Terabyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1000000000000"),
    ),
    UnitDTO(
        symbol="PB",
        name="Petabyte",
        dimensionality=Dimensionality.DIGITAL_STORAGE,
        base_unit="B",
        scale_factor_to_base=Decimal("1000000000000000"),
    ),
    # Data Rate / Bandwidth (Base: bps)
    UnitDTO(
        symbol="bps",
        name="Bits per second",
        dimensionality=Dimensionality.DATA_RATE,
        base_unit="bps",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="Kbps",
        name="Kilobits per second",
        dimensionality=Dimensionality.DATA_RATE,
        base_unit="bps",
        scale_factor_to_base=Decimal("1000"),
    ),
    UnitDTO(
        symbol="Mbps",
        name="Megabits per second",
        dimensionality=Dimensionality.DATA_RATE,
        base_unit="bps",
        scale_factor_to_base=Decimal("1000000"),
    ),
    UnitDTO(
        symbol="Gbps",
        name="Gigabits per second",
        dimensionality=Dimensionality.DATA_RATE,
        base_unit="bps",
        scale_factor_to_base=Decimal("1000000000"),
    ),
    UnitDTO(
        symbol="Tbps",
        name="Terabits per second",
        dimensionality=Dimensionality.DATA_RATE,
        base_unit="bps",
        scale_factor_to_base=Decimal("1000000000000"),
    ),
    # Time (Base: second)
    UnitDTO(
        symbol="second",
        name="Second",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="seconds",
        name="Seconds",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="minute",
        name="Minute",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("60"),
    ),
    UnitDTO(
        symbol="minutes",
        name="Minutes",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("60"),
    ),
    UnitDTO(
        symbol="hour",
        name="Hour",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("3600"),
    ),
    UnitDTO(
        symbol="hours",
        name="Hours",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("3600"),
    ),
    UnitDTO(
        symbol="day",
        name="Day",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("86400"),
    ),
    UnitDTO(
        symbol="days",
        name="Days",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("86400"),
    ),
    # Standard cloud billing month = 730 hours = 2,628,000 seconds
    UnitDTO(
        symbol="month",
        name="Billing Month (730h)",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("2628000"),
    ),
    UnitDTO(
        symbol="months",
        name="Billing Months (730h)",
        dimensionality=Dimensionality.TIME,
        base_unit="second",
        scale_factor_to_base=Decimal("2628000"),
    ),
    # Time Storage / Capacity over Time (Base: GB-hour)
    # 1 GB-hour = 1 GB stored for 1 hour.
    # 1 GB-month = 1 GB stored for 730 hours = 730 GB-hours.
    # 1 TB-month = 1000 GB-months = 730,000 GB-hours.
    UnitDTO(
        symbol="GB-hour",
        name="Gigabyte-Hour",
        dimensionality=Dimensionality.TIME_STORAGE,
        base_unit="GB-hour",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="GB-month",
        name="Gigabyte-Month",
        dimensionality=Dimensionality.TIME_STORAGE,
        base_unit="GB-hour",
        scale_factor_to_base=Decimal("730"),
    ),
    UnitDTO(
        symbol="TB-month",
        name="Terabyte-Month",
        dimensionality=Dimensionality.TIME_STORAGE,
        base_unit="GB-hour",
        scale_factor_to_base=Decimal("730000"),
    ),
    UnitDTO(
        symbol="GiB-hour",
        name="Gibibyte-Hour",
        dimensionality=Dimensionality.TIME_STORAGE,
        base_unit="GB-hour",
        scale_factor_to_base=Decimal("1.073741824"),
    ),
    UnitDTO(
        symbol="GiB-month",
        name="Gibibyte-Month",
        dimensionality=Dimensionality.TIME_STORAGE,
        base_unit="GB-hour",
        scale_factor_to_base=Decimal("783.83153152"),
    ),
    # Compute Capacity (Base: vCPU-hours)
    UnitDTO(
        symbol="vCPU-hours",
        name="vCPU Hours",
        dimensionality=Dimensionality.COMPUTE_CAPACITY,
        base_unit="vCPU-hours",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="core-hours",
        name="Core Hours",
        dimensionality=Dimensionality.COMPUTE_CAPACITY,
        base_unit="vCPU-hours",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="OCPU-hours",
        name="OCPU Hours (2 vCPUs)",
        dimensionality=Dimensionality.COMPUTE_CAPACITY,
        base_unit="vCPU-hours",
        scale_factor_to_base=Decimal("2"),
    ),
    UnitDTO(
        symbol="node-hours",
        name="Node Hours",
        dimensionality=Dimensionality.COMPUTE_CAPACITY,
        base_unit="vCPU-hours",
        scale_factor_to_base=Decimal("1"),
    ),
    # Discrete Counts & Dimensionless (Base: units)
    UnitDTO(
        symbol="units",
        name="Units",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="requests",
        name="Requests",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="calls",
        name="API Calls",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="transactions",
        name="Transactions",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="messages",
        name="Messages",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="operations",
        name="Operations",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="users",
        name="Users / Seats",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="licences",
        name="Licences",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="instances",
        name="Instances",
        dimensionality=Dimensionality.COUNT,
        base_unit="units",
        scale_factor_to_base=Decimal("1"),
    ),
    # Percentage (Base: percentage)
    UnitDTO(
        symbol="percentage",
        name="Percentage",
        dimensionality=Dimensionality.PERCENTAGE,
        base_unit="percentage",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="percent",
        name="Percent",
        dimensionality=Dimensionality.PERCENTAGE,
        base_unit="percentage",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="ratio",
        name="Fractional Ratio",
        dimensionality=Dimensionality.PERCENTAGE,
        base_unit="percentage",
        scale_factor_to_base=Decimal("100"),
    ),
    # Currencies (Base: USD)
    UnitDTO(
        symbol="USD",
        name="US Dollar",
        dimensionality=Dimensionality.CURRENCY,
        base_unit="USD",
        scale_factor_to_base=Decimal("1"),
    ),
    UnitDTO(
        symbol="EUR",
        name="Euro",
        dimensionality=Dimensionality.CURRENCY,
        base_unit="USD",
        scale_factor_to_base=Decimal("1.08"),
    ),
    UnitDTO(
        symbol="GBP",
        name="British Pound",
        dimensionality=Dimensionality.CURRENCY,
        base_unit="USD",
        scale_factor_to_base=Decimal("1.30"),
    ),
]


# ==============================================================================
# 3. Core Metric Catalogue Seeds
# ==============================================================================

SEED_METRICS: list[MetricDTO] = [
    MetricDTO(
        code="cpu_utilization_percentage",
        display_name="CPU Utilization",
        unit_symbol="percentage",
        aggregation_method=AggregationMethod.AVERAGE,
        applicable_monitoring_types=["COMPUTE_HOST", "DATABASE_INSTANCE", "SERVERLESS_CONTAINER"],
        description="Average percentage of allocated CPU in use.",
    ),
    MetricDTO(
        code="memory_utilization_percentage",
        display_name="Memory Utilization",
        unit_symbol="percentage",
        aggregation_method=AggregationMethod.AVERAGE,
        applicable_monitoring_types=["COMPUTE_HOST", "DATABASE_INSTANCE"],
        description="Average percentage of available physical RAM consumed.",
    ),
    MetricDTO(
        code="disk_read_bytes",
        display_name="Disk Read Volume",
        unit_symbol="bytes",
        aggregation_method=AggregationMethod.SUM,
        applicable_monitoring_types=["COMPUTE_HOST", "STORAGE_STORE", "DATABASE_INSTANCE"],
        description="Cumulative volume of bytes read from attached disks.",
    ),
    MetricDTO(
        code="disk_write_bytes",
        display_name="Disk Write Volume",
        unit_symbol="bytes",
        aggregation_method=AggregationMethod.SUM,
        applicable_monitoring_types=["COMPUTE_HOST", "STORAGE_STORE", "DATABASE_INSTANCE"],
        description="Cumulative volume of bytes written to attached disks.",
    ),
    MetricDTO(
        code="network_in_bytes",
        display_name="Network Ingress Bytes",
        unit_symbol="bytes",
        aggregation_method=AggregationMethod.SUM,
        applicable_monitoring_types=["COMPUTE_HOST", "NETWORK_GATEWAY", "LOAD_BALANCER"],
        description="Total inbound network traffic received across all interfaces.",
    ),
    MetricDTO(
        code="network_out_bytes",
        display_name="Network Egress Bytes",
        unit_symbol="bytes",
        aggregation_method=AggregationMethod.SUM,
        applicable_monitoring_types=["COMPUTE_HOST", "NETWORK_GATEWAY", "LOAD_BALANCER"],
        description="Total outbound network traffic transmitted across all interfaces.",
    ),
    MetricDTO(
        code="api_request_count",
        display_name="API Request Count",
        unit_symbol="requests",
        aggregation_method=AggregationMethod.SUM,
        applicable_monitoring_types=["API_GATEWAY", "SERVERLESS_FUNCTION", "LOAD_BALANCER"],
        description="Total HTTP or RPC invocation requests handled.",
    ),
    MetricDTO(
        code="storage_allocated_bytes",
        display_name="Storage Allocated",
        unit_symbol="bytes",
        aggregation_method=AggregationMethod.LAST,
        applicable_monitoring_types=["STORAGE_STORE", "DATABASE_INSTANCE"],
        description="Point-in-time provisioned storage capacity in bytes.",
    ),
]


# ==============================================================================
# 4. Pricing Dimension Catalogue Seeds (All 29 Dimensions from Reconciled Taxonomy)
# ==============================================================================

SEED_PRICING_DIMENSIONS: list[PricingDimensionDTO] = [
    PricingDimensionDTO(
        code="DIM-01",
        name="Per-second",
        category="Consumption Unit",
        unit_symbol="seconds",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Runtime seconds / hours",
        example_services="AWS Lambda, GCP Cloud Run, Azure Container Instances (per-sec duration)",
        notes="Standard sub-minute serverless runtime consumption.",
    ),
    PricingDimensionDTO(
        code="DIM-02",
        name="Per-minute",
        category="Consumption Unit",
        unit_symbol="minutes",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Runtime minutes / hours",
        example_services="Azure Container Apps, Amazon Connect voice minutes, Twilio telephony",
        notes="Discrete unit for sub-hourly managed services.",
    ),
    PricingDimensionDTO(
        code="DIM-03",
        name="Per-hour",
        category="Consumption Unit",
        unit_symbol="hours",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Runtime hours",
        example_services="Amazon EC2, Azure Virtual Machines, GCP Compute Engine, OCI Compute",
        notes="Standard compute and instance runtime measurement unit.",
    ),
    PricingDimensionDTO(
        code="DIM-04",
        name="Per-instance",
        category="Consumption Unit",
        unit_symbol="instances",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Instance count",
        example_services="AWS NAT Gateway, Azure Bastion, GCP Cloud NAT, OCI Load Balancer",
        notes="Fixed provisioned appliance / managed gateway unit.",
    ),
    PricingDimensionDTO(
        code="DIM-05",
        name="Per-request",
        category="Consumption Unit",
        unit_symbol="requests",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Request volume",
        example_services="Amazon S3 GET/PUT, Azure Blob Operations, Google Cloud Storage operations",
        notes="Object storage and serverless invocation requests.",
    ),
    PricingDimensionDTO(
        code="DIM-06",
        name="Per-API-call",
        category="Consumption Unit",
        unit_symbol="calls",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Call volume",
        example_services="Amazon API Gateway, Azure API Management, Google Cloud Endpoints",
        notes="Managed API calls and cognitive/AI invocation endpoints.",
    ),
    PricingDimensionDTO(
        code="DIM-07",
        name="Per-transaction",
        category="Consumption Unit",
        unit_symbol="transactions",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Transaction volume",
        example_services="Amazon Aurora Serverless ACU, Cosmos DB RU/s, Google Cloud Spanner",
        notes="Database and transaction processing operations.",
    ),
    PricingDimensionDTO(
        code="DIM-08",
        name="Per-message",
        category="Consumption Unit",
        unit_symbol="messages",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Message volume",
        example_services="Amazon SQS, Azure Service Bus, GCP Pub/Sub, OCI Streaming",
        notes="Event and message ingestion units.",
    ),
    PricingDimensionDTO(
        code="DIM-09",
        name="Per-operation",
        category="Consumption Unit",
        unit_symbol="operations",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Operation volume",
        example_services="AWS KMS crypto operations, Azure Key Vault ops, DynamoDB Read/Write Units",
        notes="Cryptographic and granular table operations.",
    ),
    PricingDimensionDTO(
        code="DIM-10",
        name="Per-GB",
        category="Consumption Unit",
        unit_symbol="GB",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Volume / Throughput",
        example_services="AWS Transit Gateway data processed, Azure Event Hubs ingress, Cloud NAT data",
        notes="Data processed / transient data volume.",
    ),
    PricingDimensionDTO(
        code="DIM-11",
        name="Per-GB-month",
        category="Consumption Unit",
        unit_symbol="GB-month",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Capacity (Storage)",
        example_services="Amazon EBS, Azure Managed Disks, Google Persistent Disk, OCI Block Volume",
        notes="Standard storage persistence over time.",
    ),
    PricingDimensionDTO(
        code="DIM-12",
        name="Per-TB",
        category="Consumption Unit",
        unit_symbol="TB",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Capacity / Query Volume",
        example_services="Google BigQuery data scanned, AWS Athena TB scanned, Snowflake storage",
        notes="High-volume analytical query and petabyte storage unit.",
    ),
    PricingDimensionDTO(
        code="DIM-13",
        name="Per-data-transfer-unit",
        category="Consumption Unit",
        unit_symbol="GB",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Transfer volume",
        example_services="AWS Internet Egress, Azure Egress, GCP Inter-region Data Transfer, OCI Egress",
        notes="Cross-region, cross-AZ, and internet outbound data movement.",
    ),
    PricingDimensionDTO(
        code="DIM-14",
        name="Per-CPU",
        category="Consumption Unit",
        unit_symbol="core-hours",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Core count",
        example_services="OCI OCPU, Bare Metal Cores, VMware Cloud on AWS, Dedicated Hosts",
        notes="Physical and socket-level processor allocations.",
    ),
    PricingDimensionDTO(
        code="DIM-15",
        name="Per-vCPU-hour",
        category="Consumption Unit",
        unit_symbol="vCPU-hours",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Consumption units",
        example_services="AWS Fargate vCPU-hours, Azure Container Instances vCPU-hours, Cloud Run vCPU-seconds",
        notes="Serverless and containerized virtual CPU execution.",
    ),
    PricingDimensionDTO(
        code="DIM-16",
        name="Per-node-hour",
        category="Consumption Unit",
        unit_symbol="node-hours",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Node count / hours",
        example_services="Amazon EKS managed nodes, Azure AKS node pools, Google GKE Standard, Amazon Redshift",
        notes="Managed cluster worker node runtime.",
    ),
    PricingDimensionDTO(
        code="DIM-17",
        name="Per-user",
        category="Consumption Unit",
        unit_symbol="users",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Seat count",
        example_services="Amazon QuickSight Authors, Azure DevOps Basic, Microsoft 365, Power BI Pro",
        notes="User-based seat licensing.",
    ),
    PricingDimensionDTO(
        code="DIM-18",
        name="Per-licence",
        category="Consumption Unit",
        unit_symbol="licences",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Licence count",
        example_services="Red Hat Enterprise Linux on Cloud, SUSE Linux, SQL Server BYOL / per-core",
        notes="Software licensing and bring-your-own-licence models.",
    ),
    PricingDimensionDTO(
        code="DIM-19",
        name="Subscription",
        category="Structural Pricing Model",
        unit_symbol="units",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Presence and renewal",
        example_services="AWS Enterprise Support, Azure Support Plans, Marketplace SaaS monthly subscriptions",
        notes="Fixed recurring monthly or annual platform fees.",
    ),
    PricingDimensionDTO(
        code="DIM-20",
        name="Commitment",
        category="Structural Pricing Model",
        unit_symbol="units",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Coverage and utilisation",
        example_services="AWS Compute Savings Plans, Azure Savings Plans, Google Committed Use Contracts",
        notes="Contractual minimum spend or capacity agreements.",
    ),
    PricingDimensionDTO(
        code="DIM-21",
        name="Reservation",
        category="Structural Pricing Model",
        unit_symbol="instances",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Coverage and utilisation",
        example_services="AWS Reserved Instances (1-yr/3-yr), Azure Reserved VM Instances, OCI Reserved Capacity",
        notes="Pre-purchased capacity reservations.",
    ),
    PricingDimensionDTO(
        code="DIM-22",
        name="Savings plan",
        category="Structural Pricing Model",
        unit_symbol="USD",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Spend utilisation",
        example_services="AWS EC2 Instance Savings Plans, AWS SageMaker Savings Plans, Azure Savings Plan for Compute",
        notes="Spend-based flexible compute commitment ($/hr).",
    ),
    PricingDimensionDTO(
        code="DIM-23",
        name="Minimum commitment",
        category="Structural Pricing Model",
        unit_symbol="USD",
        aggregation_method=AggregationMethod.MAX,
        default_threshold_basis="Under-consumption risk",
        example_services="Enterprise Agreement annual minimums, Snowflake annual capacity commits",
        notes="Contractual floor spend requirements.",
    ),
    PricingDimensionDTO(
        code="DIM-24",
        name="Tiered pricing",
        category="Structural Pricing Model",
        unit_symbol="units",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Tier boundary proximity",
        example_services="AWS S3 Standard Storage (First 50 TB, Next 450 TB, Over 500 TB)",
        notes="Graduated rate scales where incremental usage falls into cheaper price brackets.",
    ),
    PricingDimensionDTO(
        code="DIM-25",
        name="Volume pricing",
        category="Structural Pricing Model",
        unit_symbol="units",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Discount realisation",
        example_services="CloudFront high-volume traffic tiers, Twilio volume discounts",
        notes="All-units discount triggered when total usage exceeds volume thresholds.",
    ),
    PricingDimensionDTO(
        code="DIM-26",
        name="Free tier",
        category="Structural Pricing Model",
        unit_symbol="units",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Allowance exhaustion",
        example_services="AWS Always Free (Lambda 1M req), Azure Free Services (750 hrs B1s), GCP Free Tier, OCI Always Free",
        notes="Included monthly allowance before billable rates activate.",
    ),
    PricingDimensionDTO(
        code="DIM-27",
        name="Sustained-use pricing",
        category="Pricing Qualifier / Modifier",
        unit_symbol="percentage",
        aggregation_method=AggregationMethod.AVERAGE,
        default_threshold_basis="Runtime discount curve",
        example_services="Google Cloud Compute Engine Sustained Use Discounts (SUD)",
        notes="Automated discount applied dynamically as monthly VM running percentage increases.",
    ),
    PricingDimensionDTO(
        code="DIM-28",
        name="Promotional pricing",
        category="Pricing Qualifier / Modifier",
        unit_symbol="USD",
        aggregation_method=AggregationMethod.SUM,
        default_threshold_basis="Promotion expiry / credit depletion",
        example_services="New service trial periods, promotional SKU discounts, AWS Activate credits",
        notes="Time-limited discounted rates or vendor credit mechanisms.",
    ),
    PricingDimensionDTO(
        code="DIM-29",
        name="Region-specific pricing",
        category="Pricing Qualifier / Modifier",
        unit_symbol="ratio",
        aggregation_method=AggregationMethod.LAST,
        default_threshold_basis="Regional variance",
        example_services="AWS us-east-1 vs ap-south-1 VM pricing, Azure East US vs West Europe rate variance",
        notes="Geographic rate variance for identical SKUs across provider datacenter regions.",
    ),
]


# ==============================================================================
# 5. Core Canonical Services & Mappings
# ==============================================================================

SEED_SERVICES: list[ServiceDTO] = [
    ServiceDTO(
        id="svc-compute-vm",
        provider="canonical",
        service_code="VirtualMachines",
        name="Virtual Machines",
        category="COMPUTE",
    ),
    ServiceDTO(
        id="svc-storage-obj",
        provider="canonical",
        service_code="ObjectStorage",
        name="Object Storage",
        category="STORAGE",
    ),
    ServiceDTO(
        id="svc-database-sql",
        provider="canonical",
        service_code="RelationalDatabase",
        name="Relational Database",
        category="DATABASE",
    ),
    ServiceDTO(
        id="svc-serverless-fn",
        provider="canonical",
        service_code="ServerlessFunctions",
        name="Serverless Functions",
        category="COMPUTE",
    ),
    ServiceDTO(
        id="svc-network-gw",
        provider="canonical",
        service_code="NetworkGateway",
        name="Network Gateway",
        category="NETWORKING",
    ),
]

SEED_SERVICE_MAPPINGS: list[ServiceMappingDTO] = [
    # AWS
    ServiceMappingDTO(
        id="smap-aws-ec2",
        service_id="svc-compute-vm",
        provider="aws",
        native_service_name="AmazonEC2",
    ),
    ServiceMappingDTO(
        id="smap-aws-s3",
        service_id="svc-storage-obj",
        provider="aws",
        native_service_name="AmazonS3",
    ),
    ServiceMappingDTO(
        id="smap-aws-rds",
        service_id="svc-database-sql",
        provider="aws",
        native_service_name="AmazonRDS",
    ),
    ServiceMappingDTO(
        id="smap-aws-lambda",
        service_id="svc-serverless-fn",
        provider="aws",
        native_service_name="AWSLambda",
    ),
    # Azure
    ServiceMappingDTO(
        id="smap-az-vm",
        service_id="svc-compute-vm",
        provider="azure",
        native_service_name="Microsoft.Compute",
    ),
    ServiceMappingDTO(
        id="smap-az-blob",
        service_id="svc-storage-obj",
        provider="azure",
        native_service_name="Microsoft.Storage",
    ),
    ServiceMappingDTO(
        id="smap-az-sql",
        service_id="svc-database-sql",
        provider="azure",
        native_service_name="Microsoft.Sql",
    ),
    # GCP
    ServiceMappingDTO(
        id="smap-gcp-ce",
        service_id="svc-compute-vm",
        provider="gcp",
        native_service_name="Compute Engine",
    ),
    ServiceMappingDTO(
        id="smap-gcp-gcs",
        service_id="svc-storage-obj",
        provider="gcp",
        native_service_name="Cloud Storage",
    ),
    ServiceMappingDTO(
        id="smap-gcp-sql",
        service_id="svc-database-sql",
        provider="gcp",
        native_service_name="Cloud SQL",
    ),
    # OCI
    ServiceMappingDTO(
        id="smap-oci-compute",
        service_id="svc-compute-vm",
        provider="oci",
        native_service_name="compute",
    ),
    ServiceMappingDTO(
        id="smap-oci-storage",
        service_id="svc-storage-obj",
        provider="oci",
        native_service_name="objectstorage",
    ),
]


# ==============================================================================
# 6. Canonical Resource Types & Default Monitoring Types
# ==============================================================================

SEED_RESOURCE_TYPES: list[ResourceTypeDTO] = [
    # AWS
    ResourceTypeDTO(
        id="rt-aws-ec2-instance",
        provider="aws",
        service_id="svc-compute-vm",
        native_type_name="AWS::EC2::Instance",
        canonical_type="VIRTUAL_MACHINE",
        service_category="COMPUTE",
        default_monitoring_type="COMPUTE_HOST",
    ),
    ResourceTypeDTO(
        id="rt-aws-s3-bucket",
        provider="aws",
        service_id="svc-storage-obj",
        native_type_name="AWS::S3::Bucket",
        canonical_type="OBJECT_STORAGE_BUCKET",
        service_category="STORAGE",
        default_monitoring_type="STORAGE_STORE",
    ),
    ResourceTypeDTO(
        id="rt-aws-rds-db",
        provider="aws",
        service_id="svc-database-sql",
        native_type_name="AWS::RDS::DBInstance",
        canonical_type="SQL_DATABASE",
        service_category="DATABASE",
        default_monitoring_type="DATABASE_INSTANCE",
    ),
    ResourceTypeDTO(
        id="rt-aws-lambda-fn",
        provider="aws",
        service_id="svc-serverless-fn",
        native_type_name="AWS::Lambda::Function",
        canonical_type="SERVERLESS_FUNCTION",
        service_category="COMPUTE",
        default_monitoring_type="SERVERLESS_CONTAINER",
    ),
    # Azure
    ResourceTypeDTO(
        id="rt-az-vm",
        provider="azure",
        service_id="svc-compute-vm",
        native_type_name="Microsoft.Compute/virtualMachines",
        canonical_type="VIRTUAL_MACHINE",
        service_category="COMPUTE",
        default_monitoring_type="COMPUTE_HOST",
    ),
    ResourceTypeDTO(
        id="rt-az-storage-acct",
        provider="azure",
        service_id="svc-storage-obj",
        native_type_name="Microsoft.Storage/storageAccounts",
        canonical_type="OBJECT_STORAGE_BUCKET",
        service_category="STORAGE",
        default_monitoring_type="STORAGE_STORE",
    ),
    ResourceTypeDTO(
        id="rt-az-sql-db",
        provider="azure",
        service_id="svc-database-sql",
        native_type_name="Microsoft.Sql/servers/databases",
        canonical_type="SQL_DATABASE",
        service_category="DATABASE",
        default_monitoring_type="DATABASE_INSTANCE",
    ),
    # GCP
    ResourceTypeDTO(
        id="rt-gcp-compute-instance",
        provider="gcp",
        service_id="svc-compute-vm",
        native_type_name="compute.googleapis.com/Instance",
        canonical_type="VIRTUAL_MACHINE",
        service_category="COMPUTE",
        default_monitoring_type="COMPUTE_HOST",
    ),
    ResourceTypeDTO(
        id="rt-gcp-storage-bucket",
        provider="gcp",
        service_id="svc-storage-obj",
        native_type_name="storage.googleapis.com/Bucket",
        canonical_type="OBJECT_STORAGE_BUCKET",
        service_category="STORAGE",
        default_monitoring_type="STORAGE_STORE",
    ),
    # OCI
    ResourceTypeDTO(
        id="rt-oci-instance",
        provider="oci",
        service_id="svc-compute-vm",
        native_type_name="instance",
        canonical_type="VIRTUAL_MACHINE",
        service_category="COMPUTE",
        default_monitoring_type="COMPUTE_HOST",
    ),
    ResourceTypeDTO(
        id="rt-oci-bucket",
        provider="oci",
        service_id="svc-storage-obj",
        native_type_name="bucket",
        canonical_type="OBJECT_STORAGE_BUCKET",
        service_category="STORAGE",
        default_monitoring_type="STORAGE_STORE",
    ),
]
