{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudlens.fullname" . }}-api
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      {{- include "cloudlens.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
