apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudlens.fullname" . }}-api
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    openbao.security.internal/role: {{ .Values.serviceAccounts.openbaoRolePrefix | default "cloudlens" }}-api
    openbao.security.internal/vault-path: {{ .Values.external.openbao.databaseSecretPath | quote }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudlens.fullname" . }}-worker
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  annotations:
    openbao.security.internal/role: {{ .Values.serviceAccounts.openbaoRolePrefix | default "cloudlens" }}-worker
    openbao.security.internal/vault-path: {{ .Values.external.openbao.redisSecretPath | quote }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudlens.fullname" . }}-beat
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
  annotations:
    openbao.security.internal/role: {{ .Values.serviceAccounts.openbaoRolePrefix | default "cloudlens" }}-beat
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudlens.fullname" . }}-jobs
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: jobs
  annotations:
    openbao.security.internal/role: {{ .Values.serviceAccounts.openbaoRolePrefix | default "cloudlens" }}-jobs
automountServiceAccountToken: true
