apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudlens.fullname" . }}-web
  labels:
    {{- include "cloudlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.web.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudlens.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
