"""Master Registry Manifest for CloudLens.

Enforces Prompt 45 Item 2:
- Manifest declaring every master in the system.
- Purpose, schema, global/tenant-scoped, editable, approval requirement, consuming modules, seed file.
- Rule: Nothing may be a master without appearing in the registry.
"""

from masterdata.models import MasterRegistryEntry

# ==============================================================================
# Master Registry Manifest
# ==============================================================================

SYSTEM_MASTER_REGISTRY: dict[str, MasterRegistryEntry] = {
    "SERVICE_CATEGORY": MasterRegistryEntry(
        code="SERVICE_CATEGORY",
        name="FOCUS Service Categories",
        purpose="Classifies cloud services into standardized taxonomy aligned to FOCUS 1.0.",
        schema_def={"is_focus_standard": "boolean"},
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["normalisation", "pricing", "ingestion", "reporting"],
        seed_file="masterdata/seeds/service_category.json",
        expected_review_period_days=180,
    ),
    "RESOURCE_TYPE": MasterRegistryEntry(
        code="RESOURCE_TYPE",
        name="Canonical Resource Types",
        purpose="Defines canonical infrastructure resource types and default monitoring roles.",
        schema_def={"default_monitoring_type": "string", "service_category": "string"},
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "connectors", "normalisation", "monitoring"],
        seed_file="masterdata/seeds/resource_type.json",
        expected_review_period_days=90,
    ),
    "UNIT": MasterRegistryEntry(
        code="UNIT",
        name="Units of Measurement",
        purpose="Defines canonical symbols, dimensionality, and declarative conversion factors.",
        schema_def={
            "dimensionality": "string",
            "base_unit": "string",
            "scale_factor_to_base": "number",
            "offset_to_base": "number",
        },
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["normalisation", "pricing", "usage", "reporting"],
        seed_file="masterdata/seeds/unit.json",
        expected_review_period_days=180,
    ),
    "METRIC": MasterRegistryEntry(
        code="METRIC",
        name="Metric Catalogue",
        purpose="Defines operational metrics, aggregation methods, and applicable monitoring types.",
        schema_def={
            "unit_symbol": "string",
            "aggregation_method": "string",
            "applicable_monitoring_types": "array",
        },
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["monitoring", "runtime", "thresholds"],
        seed_file="masterdata/seeds/metric.json",
        expected_review_period_days=180,
    ),
    "PRICING_DIMENSION": MasterRegistryEntry(
        code="PRICING_DIMENSION",
        name="Reconciled Pricing Dimensions",
        purpose="Taxonomy of 29 pricing dimensions and models across consumption, structure, and qualifiers.",
        schema_def={
            "category": "string",
            "unit_symbol": "string",
            "aggregation_method": "string",
            "default_threshold_basis": "string",
            "is_custom_escape_hatch": "boolean",
            "provider_code": "string",
        },
        is_tenant_scoped=True,  # Tenants/providers can register custom escape hatch dimensions
        is_editable=True,
        requires_approval=True,
        consuming_modules=["pricing", "billing", "cost", "budgeting"],
        seed_file="masterdata/seeds/pricing_dimension.json",
        expected_review_period_days=90,
    ),
    "CLOUD_PROVIDER": MasterRegistryEntry(
        code="CLOUD_PROVIDER",
        name="Cloud Providers",
        purpose="Supported hyperscale cloud service providers and canonical boundaries.",
        schema_def={"api_endpoint": "string", "icon": "string"},
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["connectors", "ingestion", "auth", "inventory"],
        seed_file="masterdata/seeds/cloud_provider.json",
        expected_review_period_days=365,
    ),
    "RUNTIME_STATUS": MasterRegistryEntry(
        code="RUNTIME_STATUS",
        name="Resource Runtime Status",
        purpose="Canonical operational lifecycle states for compute, database, and container resources.",
        schema_def={"is_billable": "boolean", "color_hex": "string"},
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["inventory", "monitoring", "runtime", "recommendations"],
        seed_file="masterdata/seeds/runtime_status.json",
        expected_review_period_days=365,
    ),
    "CHARGE_CATEGORY": MasterRegistryEntry(
        code="CHARGE_CATEGORY",
        name="FOCUS Charge Categories",
        purpose="Standardized billing charge classifications (Usage, Purchase, Adjustment, Tax, Credit).",
        schema_def={"is_recurring": "boolean"},
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["billing", "cost", "amortisation", "reporting"],
        seed_file="masterdata/seeds/charge_category.json",
        expected_review_period_days=365,
    ),
    "PRICING_STATUS": MasterRegistryEntry(
        code="PRICING_STATUS",
        name="Resource Pricing Statuses",
        purpose="Seven canonical pricing classifications per BBP Section 16 (FREE, PAID, ESTIMATED, etc.).",
        schema_def={"requires_rate_lookup": "boolean"},
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["inventory", "pricing", "cost"],
        seed_file="masterdata/seeds/pricing_status.json",
        expected_review_period_days=365,
    ),
    "POLICY_SEVERITY": MasterRegistryEntry(
        code="POLICY_SEVERITY",
        name="Governance Policy Severities",
        purpose="Severity ranking for compliance, security, and cost anomaly policy violations.",
        schema_def={"sla_hours": "number", "level_order": "number"},
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["governance", "alerting", "notifications"],
        seed_file="masterdata/seeds/policy_severity.json",
        expected_review_period_days=180,
    ),
    "THRESHOLD_BAND": MasterRegistryEntry(
        code="THRESHOLD_BAND",
        name="Threshold Evaluation Bands",
        purpose="Standardized threshold evaluation states (Nominal, Warning, Critical, Exceeded).",
        schema_def={"urgency": "string", "triggers_alert": "boolean"},
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["budgeting", "alerting", "monitoring"],
        seed_file="masterdata/seeds/threshold_band.json",
        expected_review_period_days=180,
    ),
    # ==========================================================================
    # Organisation Masters (Prompt 46 Item 11)
    # ==========================================================================
    "BUSINESS_UNIT": MasterRegistryEntry(
        code="BUSINESS_UNIT",
        name="Business Units",
        purpose="Hierarchical organisational division units with operational ownership and effective dates.",
        schema_def={"head_of_unit": "string", "cost_centre_prefix": "string"},
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["allocation", "budgeting", "reporting", "governance"],
        seed_file="masterdata/seeds/business_unit.json",
        expected_review_period_days=180,
    ),
    "COST_CENTRE": MasterRegistryEntry(
        code="COST_CENTRE",
        name="Cost Centres",
        purpose="Financial cost centres linked to business units, GL accounts, owners, and validity periods.",
        schema_def={
            "business_unit_code": "string",
            "gl_account_reference": "string",
            "owner_id": "string",
            "validity_start": "string",
            "validity_end": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["billing", "allocation", "budgeting", "cost"],
        seed_file="masterdata/seeds/cost_centre.json",
        expected_review_period_days=180,
    ),
    "DEPARTMENT": MasterRegistryEntry(
        code="DEPARTMENT",
        name="Departments",
        purpose="Functional organisational departments within legal entities and business units.",
        schema_def={
            "division": "string",
            "head_of_department": "string",
            "cost_centre_code": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["governance", "inventory", "allocation"],
        seed_file="masterdata/seeds/department.json",
        expected_review_period_days=180,
    ),
    "LEGAL_ENTITY": MasterRegistryEntry(
        code="LEGAL_ENTITY",
        name="Legal Entities",
        purpose="Incorporated corporate entities and jurisdictions for tax and compliance.",
        schema_def={
            "jurisdiction": "string",
            "registration_number": "string",
            "currency": "string",
            "tax_id": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["billing", "contracts", "reporting", "compliance"],
        seed_file="masterdata/seeds/legal_entity.json",
        expected_review_period_days=365,
    ),
    "LOCATION": MasterRegistryEntry(
        code="LOCATION",
        name="Sites and Locations",
        purpose="Corporate sites, regional hubs, and datacenters associated with local calendars.",
        schema_def={
            "country_code": "string",
            "city": "string",
            "site_type": "string",
            "timezone": "string",
            "holiday_calendar_code": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["inventory", "schedule_adherence", "reporting"],
        seed_file="masterdata/seeds/location.json",
        expected_review_period_days=365,
    ),
    "PROJECT": MasterRegistryEntry(
        code="PROJECT",
        name="Projects & Initiatives",
        purpose="Projects with start/end dates, capitalisation status, and cost centre attribution.",
        schema_def={
            "start_date": "string",
            "end_date": "string",
            "sponsor_id": "string",
            "is_capitalised": "boolean",
            "cost_centre_code": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["allocation", "budgeting", "amortisation", "reporting"],
        seed_file="masterdata/seeds/project.json",
        expected_review_period_days=90,
    ),
    # ==========================================================================
    # Application, Owner/Team and Environment Masters (Items 12, 13, 14)
    # ==========================================================================
    "APPLICATION": MasterRegistryEntry(
        code="APPLICATION",
        name="Application Catalogue",
        purpose="Enterprise applications with criticality, ownership, environment sets, and provider tags.",
        schema_def={
            "criticality_tier": "string",
            "business_owner": "string",
            "technical_owner": "string",
            "supporting_team": "string",
            "cost_centre": "string",
            "environment_set": "array",
            "lifecycle_state": "string",
            "service_level_classification": "string",
            "provider_tag_mappings": "object",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "allocation", "monitoring", "governance", "tagging"],
        seed_file="masterdata/seeds/application.json",
        expected_review_period_days=90,
    ),
    "OWNER_TEAM": MasterRegistryEntry(
        code="OWNER_TEAM",
        name="Owners and Teams",
        purpose="People and teams with contact channels, directory IDs, roles, and delegation successors.",
        schema_def={
            "entity_type": "string",
            "display_name": "string",
            "contact_channels": "object",
            "directory_reference": "string",
            "role": "string",
            "delegation_successor_id": "string",
            "out_of_office_successor_id": "string",
            "active_period_start": "string",
            "active_period_end": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["governance", "inventory", "alerting", "approvals"],
        seed_file="masterdata/seeds/owner_team.json",
        expected_review_period_days=90,
    ),
    "ENVIRONMENT": MasterRegistryEntry(
        code="ENVIRONMENT",
        name="Environments",
        purpose="Deployment environments with production flag, default schedules, thresholds, and provider tags.",
        schema_def={
            "is_production": "boolean",
            "default_schedule": "string",
            "default_threshold_profile": "string",
            "default_monitoring_posture": "string",
            "provider_tag_mappings": "object",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "runtime", "monitoring", "thresholds", "tagging"],
        seed_file="masterdata/seeds/environment.json",
        expected_review_period_days=180,
    ),
    # ==========================================================================
    # Financial Calendar Masters (Item 15)
    # ==========================================================================
    "FISCAL_CALENDAR": MasterRegistryEntry(
        code="FISCAL_CALENDAR",
        name="Fiscal Calendars",
        purpose="Financial fiscal year starts, period definitions, and close date schedules.",
        schema_def={
            "fiscal_year_start_month": "number",
            "fiscal_year_start_day": "number",
            "period_type": "string",
            "period_definitions": "array",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["budgeting", "billing", "reporting", "amortisation"],
        seed_file="masterdata/seeds/fiscal_calendar.json",
        expected_review_period_days=365,
    ),
    "HOLIDAY_CALENDAR": MasterRegistryEntry(
        code="HOLIDAY_CALENDAR",
        name="Holiday Calendars",
        purpose="Regional statutory and public holidays used to suppress schedule adherence exceptions.",
        schema_def={"location_code": "string", "year": "number", "holidays": "array"},
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["runtime", "schedule_adherence", "monitoring"],
        seed_file="masterdata/seeds/holiday_calendar.json",
        expected_review_period_days=180,
    ),
    "WORKING_WEEK": MasterRegistryEntry(
        code="WORKING_WEEK",
        name="Working Week Definitions",
        purpose="Operational working days, hours, and timezones for runtime evaluation.",
        schema_def={
            "working_days": "array",
            "daily_start_time": "string",
            "daily_end_time": "string",
            "timezone": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=False,
        consuming_modules=["runtime", "monitoring", "schedule_adherence"],
        seed_file="masterdata/seeds/working_week.json",
        expected_review_period_days=365,
    ),
    # ==========================================================================
    # Currency and Exchange-Rate Masters (Item 16)
    # ==========================================================================
    "CURRENCY": MasterRegistryEntry(
        code="CURRENCY",
        name="Currencies",
        purpose="ISO currencies with symbols, minor units, and rounding rules.",
        schema_def={"symbol": "string", "minor_units": "number", "rounding_rule": "string"},
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["billing", "pricing", "cost", "reporting"],
        seed_file="masterdata/seeds/currency.json",
        expected_review_period_days=365,
    ),
    "EXCHANGE_RATE": MasterRegistryEntry(
        code="EXCHANGE_RATE",
        name="Exchange Rates",
        purpose="Effective-dated exchange rates by rate type (spot, monthly avg, budget, constant).",
        schema_def={
            "from_currency": "string",
            "to_currency": "string",
            "rate": "string",
            "effective_date": "string",
            "rate_type": "string",
            "source": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["billing", "cost", "budgeting", "reporting"],
        seed_file="masterdata/seeds/exchange_rate.json",
        expected_review_period_days=30,
    ),
    "TENANT_FX_POLICY": MasterRegistryEntry(
        code="TENANT_FX_POLICY",
        name="Tenant FX Conversion Policies",
        purpose="Tenant policy selecting which rate type applies to each presentation context.",
        schema_def={
            "tenant_id": "string",
            "reporting_currency": "string",
            "presentation_policies": "object",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["billing", "reporting", "budgeting", "dashboard"],
        seed_file="masterdata/seeds/tenant_fx_policy.json",
        expected_review_period_days=180,
    ),
    # ==========================================================================
    # Contract, Rate-Card, Commitment and Licence Masters (Items 17, 18, 19)
    # ==========================================================================
    "CONTRACT": MasterRegistryEntry(
        code="CONTRACT",
        name="Provider Contracts & Agreements",
        purpose="Cloud provider enterprise agreements, term dates, commitments, and discount structures.",
        schema_def={
            "provider_code": "string",
            "agreement_type": "string",
            "contract_reference": "string",
            "term_start_date": "string",
            "term_end_date": "string",
            "committed_spend_amount": "string",
            "discount_structure": "object",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["pricing", "billing", "contracts", "reporting"],
        seed_file="masterdata/seeds/contract.json",
        expected_review_period_days=180,
    ),
    "RATE_CARD": MasterRegistryEntry(
        code="RATE_CARD",
        name="Rate Cards & Negotiated Rates",
        purpose="Contracted and list rates with manual-source labeling superseding provider list rates.",
        schema_def={
            "provider_code": "string",
            "service_code": "string",
            "sku_id": "string",
            "list_rate": "string",
            "contracted_rate": "string",
            "currency": "string",
            "source": "string",
            "effective_from": "string",
            "contract_reference": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["pricing", "billing", "cost"],
        seed_file="masterdata/seeds/rate_card.json",
        expected_review_period_days=90,
    ),
    "COMMITMENT": MasterRegistryEntry(
        code="COMMITMENT",
        name="Commitments & Reservations",
        purpose="Reservations, savings plans, and committed-use agreements with terms and renewal lead times.",
        schema_def={
            "provider_code": "string",
            "commitment_type": "string",
            "scope_id": "string",
            "scope_type": "string",
            "committed_units": "number",
            "unit_symbol": "string",
            "term_months": "number",
            "start_date": "string",
            "expiry_date": "string",
            "renewal_reminder_lead_time_days": "number",
            "status": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "pricing", "commitments", "monitoring"],
        seed_file="masterdata/seeds/commitment.json",
        expected_review_period_days=60,
    ),
    "LICENCE": MasterRegistryEntry(
        code="LICENCE",
        name="Software Licences",
        purpose="Software licence entitlements, assignment bases, BYOL flags, and renewal dates.",
        schema_def={
            "licence_type": "string",
            "entitlement_count": "number",
            "assignment_basis": "string",
            "is_byol": "boolean",
            "renewal_date": "string",
            "monitoring_type_code": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "monitoring", "licencing", "cost"],
        seed_file="masterdata/seeds/licence.json",
        expected_review_period_days=90,
    ),
    # ==========================================================================
    # Tag Policy and Geography Masters (Items 20, 21)
    # ==========================================================================
    "TAG_POLICY": MasterRegistryEntry(
        code="TAG_POLICY",
        name="Tag Policies & Enforcement",
        purpose="Mandatory tag keys, allowed value sets, format rules, and enforcement postures.",
        schema_def={
            "mandatory_tag_keys": "array",
            "allowed_values": "object",
            "format_rules": "object",
            "scope_applicability": "array",
            "enforcement_posture": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["governance", "tagging", "inventory", "compliance"],
        seed_file="masterdata/seeds/tag_policy.json",
        expected_review_period_days=90,
    ),
    "GEOGRAPHY": MasterRegistryEntry(
        code="GEOGRAPHY",
        name="Geographies & Jurisdictions",
        purpose="Region groupings, data residency classifications, and approved deployment regions.",
        schema_def={
            "geography_group": "string",
            "jurisdiction": "string",
            "data_residency_classification": "string",
            "provider_regions": "object",
            "is_approved_for_deployment": "boolean",
        },
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "compliance", "governance", "connectors"],
        seed_file="masterdata/seeds/geography.json",
        expected_review_period_days=180,
    ),
    # ==========================================================================
    # String Catalogue Master (Prompt 48 Item 37)
    # ==========================================================================
    "STRING_CATALOGUE": MasterRegistryEntry(
        code="STRING_CATALOGUE",
        name="Externalised String Catalogue",
        purpose="User-facing display strings, navigation labels, help text, explanation text, and notifications.",
        schema_def={
            "locale": "string",
            "category": "string",
            "template": "string",
            "fallback_en": "string",
            "variables": "array",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["presentation", "ui", "i18n", "notifications", "reporting"],
        seed_file="masterdata/seeds/string_catalogue.json",
        expected_review_period_days=90,
    ),
    # ==========================================================================
    # Pre-Identity System Bootstrap Masters (Prompt 49A Items 7-11)
    # ==========================================================================
    "SYSTEM_TENANT": MasterRegistryEntry(
        code="SYSTEM_TENANT",
        name="System Tenant Bootstrap Profile",
        purpose="Shipped system tenant default parameters (reporting currency, fiscal calendar, timezone, retention profile).",
        schema_def={
            "tenant_id": "string",
            "reporting_currency": "string",
            "fiscal_calendar_code": "string",
            "time_zone": "string",
            "retention_profile": "object",
        },
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["bootstrap", "config", "tenants", "governance"],
        seed_file="masterdata/seeds/system_tenant.json",
        expected_review_period_days=365,
    ),
    "PERMISSION": MasterRegistryEntry(
        code="PERMISSION",
        name="Platform Permission Catalogue",
        purpose="Fine-grained functional and administrative RBAC permissions.",
        schema_def={"domain": "string", "action": "string"},
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["security", "rbac", "auth", "api"],
        seed_file="masterdata/seeds/permission.json",
        expected_review_period_days=180,
    ),
    "ROLE": MasterRegistryEntry(
        code="ROLE",
        name="Built-In Role Definitions",
        purpose="Nine canonical enterprise FinOps role definitions and allowed permission sets.",
        schema_def={
            "is_built_in": "boolean",
            "max_scope": "string",
            "allowed_permissions": "array",
        },
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["security", "rbac", "auth", "admin"],
        seed_file="masterdata/seeds/role.json",
        expected_review_period_days=180,
    ),
    "THRESHOLD_TEMPLATE": MasterRegistryEntry(
        code="THRESHOLD_TEMPLATE",
        name="Default Threshold Templates",
        purpose="Standard threshold templates for compute idle, storage cleanup, budget warnings, and spend spikes.",
        schema_def={
            "target_monitoring_type": "string",
            "metric_code": "string",
            "operator": "string",
            "threshold_value": "number",
            "default_severity": "string",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["thresholds", "monitoring", "governance", "alerting"],
        seed_file="masterdata/seeds/threshold_template.json",
        expected_review_period_days=90,
    ),
    "BUDGET_TEMPLATE": MasterRegistryEntry(
        code="BUDGET_TEMPLATE",
        name="Default Budget Templates",
        purpose="Standard budget templates for monthly operations, quarterly projects, and environment caps.",
        schema_def={
            "period_type": "string",
            "threshold_template_codes": "array",
            "allow_overruns": "boolean",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["budgeting", "financial", "governance"],
        seed_file="masterdata/seeds/budget_template.json",
        expected_review_period_days=90,
    ),
    "POLICY": MasterRegistryEntry(
        code="POLICY",
        name="Governance Policy Catalogue",
        purpose="Standard governance policies disabled by default except connector health.",
        schema_def={
            "category": "string",
            "rule_type": "string",
            "enabled": "boolean",
            "severity": "string",
            "parameters": "object",
        },
        is_tenant_scoped=True,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["governance", "policy_engine", "connectors", "compliance"],
        seed_file="masterdata/seeds/policy.json",
        expected_review_period_days=90,
    ),
    "PROVIDER_CAPABILITY": MasterRegistryEntry(
        code="PROVIDER_CAPABILITY",
        name="Cloud Provider Capabilities",
        purpose="Discovery, inventory, cost, metrics, pricing, and quota headroom capabilities (C-01 to C-18).",
        schema_def={
            "capability_id": "string",
            "required_tier": "string",
            "supported_providers": "array",
        },
        is_tenant_scoped=False,
        is_editable=False,
        requires_approval=True,
        consuming_modules=["connectors", "inventory", "pricing", "quotas"],
        seed_file="masterdata/seeds/provider_capability.json",
        expected_review_period_days=180,
    ),
    "SERVICE": MasterRegistryEntry(
        code="SERVICE",
        name="Canonical Cloud Services",
        purpose="Core canonical service definitions across compute, storage, database, serverless, and network.",
        schema_def={"service_id": "string", "provider": "string", "category": "string"},
        is_tenant_scoped=False,
        is_editable=True,
        requires_approval=True,
        consuming_modules=["inventory", "normalisation", "pricing", "catalogues"],
        seed_file="masterdata/seeds/service.json",
        expected_review_period_days=180,
    ),
}


def get_registered_master(master_type: str) -> MasterRegistryEntry | None:
    """Retrieves registry metadata for a given master type."""
    return SYSTEM_MASTER_REGISTRY.get(master_type.strip().upper())


def list_registered_masters() -> list[MasterRegistryEntry]:
    """Returns all declared masters in the system."""
    return list(SYSTEM_MASTER_REGISTRY.values())


def is_master_registered(master_type: str) -> bool:
    """Verifies whether a master type is officially registered in the manifest."""
    return master_type.strip().upper() in SYSTEM_MASTER_REGISTRY
